### ISSUE TITLE
Font Awesome and Line Awesome icon search is mutually exclusive

### ISSUE THREAD

**Issue by programotuojes** [Ahmadre/FlutterIconPicker#80]
By providing both Font Awesome and Line Awesome icon packs:

```dart
const SinglePickerConfiguration(
  iconPackModes: [
    IconPack.lineAwesomeIcons,
    IconPack.fontAwesomeIcons,
  ],
),
```

results are displayed only for the first pack. This is because both of these icon packs have the same icon names, and when adding icons to the results map, [only the name](https://github.com/Ahmadre/FlutterIconPicker/blob/5523a730852daddb15a9110d0354d7cb14b34b7a/lib/IconPicker/search_bar.dart#L55) is taken into account.

**Comment by Ahmadre** [comment]
> By providing both Font Awesome and Line Awesome icon packs:
> 
> 
> 
> ```dart
> 
> const SinglePickerConfiguration(
> 
>   iconPackModes: [
> 
>     IconPack.lineAwesomeIcons,
> 
>     IconPack.fontAwesomeIcons,
> 
>   ],
> 
> ),
> 
> ```
> 
> 
> 
> results are displayed only for the first pack. This is because both of these icon packs have the same icon names, and when adding icons to the results map, [only the name](https://github.com/Ahmadre/FlutterIconPicker/blob/5523a730852daddb15a9110d0354d7cb14b34b7a/lib/IconPicker/search_bar.dart#L55) is taken into account.

You're totally right!

That's why I've added also the pack information to every icon.

I will update the related code sections including the one you mention.

Thank you very much for your finding 😊.

**Comment by Ahmadre** [comment]
Fixed:

<img width="502" alt="image" src="https://github.com/user-attachments/assets/dfa36bea-1c2f-4eeb-93ce-c1a3253a4d95">

**Comment by programotuojes** [comment]
It isn't fixed yet. The difference between the previous and current implementation is that now the icon from the last provided icon pack is shown instead of from the first.

![Screenshot_20240907_112710](https://github.com/user-attachments/assets/6bbfa0c6-76db-4397-ab12-a37dabb290b9)

To check if it was fixed, search for a single word named icon. "cann" seems to do the trick.

**Comment by Ahmadre** [comment]
> It isn't fixed yet. The difference between the previous and current implementation is that now the icon from the last provided icon pack is shown instead of from the first.
> 
> ![Screenshot_20240907_112710](https://private-user-images.githubusercontent.com/22987378/365353951-6bbfa0c6-76db-4397-ab12-a37dabb290b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MTQ4NzYsIm5iZiI6MTcyNTcxNDU3NiwicGF0aCI6Ii8yMjk4NzM3OC8zNjUzNTM5NTEtNmJiZmEwYzYtNzZkYi00Mzk3LWFiMTItYTM3ZGFiYjI5MGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDEzMDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ODhiNTUxZDNhZGRhN2E3MzFhNGE1Mjk4NmFjZDhmMDUwYzkzYjc5MGRhOGU2YzQ5ZTFiOTY0Zjg0ODc5NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VQpwM8dMoFsFLfi4uhA0ap_AVPEwm4iPLlBk-hWfaJ8)
> 
> To check if it was fixed, search for a single word named icon. "cann" seems to do the trick.

Yeah, it would help if you can send me the list of icon names which are exactly the same so I can reproduce it.

I will have a look at this again after I have more example then "cann".

**Comment by Ahmadre** [comment]
@programotuojes I cannot reproduce it.

I have generated font awesome and line awesome and I get all icons from both packages for "cann":

<img width="235" alt="image" src="https://github.com/user-attachments/assets/e8b5b0ca-af1d-45a7-aba9-5ff18bd4195f">

What icon are you searching for? The emoji cannabis icon is from line awesome and the letters here are from font awesome.

**Comment by Ahmadre** [comment]
I see you're looking for this icon:

<img width="268" alt="image" src="https://github.com/user-attachments/assets/67c90036-6cde-4bf7-887f-6ec542194be3">

I will fix this.

**Comment by Ahmadre** [comment]
@programotuojes Fixed:

![Unbenanntes Video](https://github.com/user-attachments/assets/202e13ac-de00-4a86-8bbe-b5437a367023)

**Comment by Ahmadre** [comment]
new version online. Let me know if you need anything else 👍
